# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-08 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myarticle', '0003_remove_article_comment'),
        ('commenting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myarticle.Article'),
        ),
    ]
