# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-07 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commenting', '0002_auto_20191107_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentss',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
