# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-08 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myarticle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
